# ================= JVM Memory Settings =================
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# ================= Gradle Performance =================
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# ================= AndroidX =================
android.useAndroidX=true
android.enableJetifier=false

# ================= React Native Architectures =================
newArchEnabled=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# ================= Hermes JS Engine =================
hermesEnabled=true

# ================= Edge-to-Edge Display =================
edgeToEdgeEnabled=true

# ================= FIX: AGP 9.0 compatibility =================
android.builtInKotlin=false
android.newDsl=false

# ================= Release Signing =================
COGGSAFE_RELEASE_STORE_FILE=coggsafe-release.keystore
COGGSAFE_RELEASE_KEY_ALIAS=coggsafe
COGGSAFE_RELEASE_STORE_PASSWORD=Sheraz@123
COGGSAFE_RELEASE_KEY_PASSWORD=Sheraz@123